site_name: Wiki Hadaria
site_description: Règlement officiel du serveur Hadaria
site_url: https://realvolgaar.github.io/hadaria-reglement/

theme:
  name: material
  language: fr
  logo: https://www.hadaria.fr/_next/image?url=%2Flogo.webp&w=96&q=75
  favicon: https://www.hadaria.fr/_next/image?url=%2Flogo.webp&w=32&q=75
  palette:
    scheme: slate
    primary: custom
    accent: deep purple
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.copy
    - toc.follow

extra_css:
  - stylesheets/extra.css

nav:
  - Accueil: index.md
  - Règlements:
    - Règlement général: reglement-general.md
    - Règlement Évents PvP: reglement-events-pvp.md
    - Règlement Farm: reglement-farm.md
    - Règlement Pillage: reglement-pillage.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - tables

plugins:
  - search:
      lang: fr

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/hadaria
      name: Discord Hadaria
